### ISSUE TITLE
Players respawn if they disconnect while dead

### ISSUE THREAD

**Issue by Shaneajm** [csgo-league/csgo-league-get5#4]
### Expected behavior
When a player disconnects, their alive state should be saved.

### Actual behavior
Player can disconnect when dead and come back alive.

### Steps to reproduce
Die during a match, disconnect during the round and then reconnect. You will come back alive.

**Comment by B3none** [comment]
We'll be able to post this issue on the get5 repository and someone over there might fix it for us.

**Comment by 39ma** [comment]
Fixed in https://github.com/csgo-league/csgo-league-game/commit/8b04d576ef14985ed3cf9731b0e7330a781af502 #
