### ISSUE TITLE
get5 already installed

### ISSUE THREAD

**Issue by ttibau** [csgo-league/csgo-league-get5#7]
Hello, 

I already have a get5 plugin running on my server, do I have to do installation of **csgo-league-get5** instead get5?

**Comment by ongloveth** [comment]
I think so.

**Comment by ttibau** [comment]
Will I have to do the entire installation or override some files? 😢

**Comment by ongloveth** [comment]
I'm not going to lie, the new install is the best way.

**Comment by ttibau** [comment]
Okay, 
Thanks, 

Closing
